<script src="/assets/bootstrap-3.3.5-dist/js/bootstrap.min.js"></script>
<script src="/assets/js/bootstrap-hover-dropdown.min.js"></script>
<script src="/assets/js/wow.min.js"></script>
<script src="/assets/js/retina-1.1.0.min.js"></script>
<script src="/assets/js/jflickrfeed.min.js"></script>
<script src="/assets/js/masonry.pkgd.min.js"></script>
<script src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script src="/assets/js/scripts.js"></script>
<script src="/assets/js/treeview.js"></script>